env:
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - 0
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
  no-eval:
    - error
  no-extra-boolean-cast:
    - error
  no-mixed-spaces-and-tabs:
    - error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
  no-unreachable:
    - error
  keyword-spacing:
    - error
  prefer-const:
    - error
    - destructuring: any
  key-spacing:
    - error
  new-cap:
    - 0
    - error
  no-array-constructor:
    - error
  no-async-promise-executor:
    - error
  no-compare-neg-zero:
    - error
  no-const-assign:
    - error
  no-constant-condition:
    - error
  no-delete-var:
    - error
  no-dupe-args:
    - error
  no-lone-blocks:
    - error
  no-multi-spaces:
    - error
  no-console:
    - warn
  no-multi-str:
    - error
  no-var:
    - error
  no-this-alias:
    - 0
  max-len:
    - error
    - code: 120
      ignoreUrls: true
      ignorePattern: ^import\s.+\sfrom\s.+;$
  curly:
    - error
  brace-style:
    - error
    - 1tbs
